import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const toNameLower = (value: string): string =>
  value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

// Colonias/barrios de Cintalapa de Figueroa, Chiapas
const neighborhoodNames = [
  'Fraccionamiento Jardines de Cintalapa',
  'Colonia Cintalapa de Figueroa Centro',
  'Colonia Urbana',
  'Colonia Insurgentes',
  'Colonia Juan Sabines',
  'Colonia Los Laureles',
  'Barrio Tepeyac',
  'Barrio Santa Cecilia',
  'Barrio San Francisco',
  'Barrio Guadalupe',
  'Fraccionamiento Paraíso',
  'Fraccionamiento Jardín Magisterial',
  'Colonia San Marcos',
  'Colonia Linda Vista',
  'Colonia Seguro Social',
  'Barrio Santa Cruz',
  'Barrio San Martín',
  'Colonia Obrera Campesina',
  'Colonia El Mirador',
  'Barrio Salomón González Blanco',
  'Colonia Ocho de Enero',
  'Barrio Santo Domingo',
  'Colonia Lomas del Oriente',
  'Fraccionamiento El Huapinol',
  'Fraccionamiento Las Garzas',
  'Fraccionamiento Albores Guillén',
  'Barrio 14 de Febrero',
  'Colonia 4 de Octubre',
  'Barrio Brasilito',
  'Colonia Buenos Aires',
  'Fraccionamiento Magisterial',
  'Barrio La Candelaria',
  'Colonia La Esmeralda',
  'Fraccionamiento Lirios del Valle',
  'Fraccionamiento Los Pinos',
  'Colonia Miguel Ángel Luna',
  'Colonia Nuevo Sinaí',
  'Fraccionamiento Portales de Cintalapa',
  'Colonia San José del Bado',
  'Colonia Unión Ejidal',
  'Ranchería Parque Ecológico Eduardo Esponda',
  'Colonia San Luis',
  'Colonia Lindavista',
  'Colonia Solo un Camino',
  'Colonia Los Pocitos',
  'Equipamiento Incubadora del Valle',
  'Rancho San Isidro',
  'Colonia Tuxtlita',
  'Ranchería Chamiapa',
  'Colonia Diez de Abril',
  'Ranchería El Framboyán',
  'Ranchería El Mirador',
  'Ranchería El nullche',
  'Ranchería Gracias a Dios',
  'Ranchería La Guirnalda',
  'Ranchería La Molienda',
  'Ranchería La Palapa del Negro',
  'Ranchería La Primavera',
  'Ranchería La Trinidad',
  'Ranchería Las Palmas',
  'Ranchería Los Cocos',
  'Colonia San Joaquín',
  'Ranchería Los Mangos',
  'Ranchería Miramar',
  'Ranchería Palmira',
  'Ranchería Rancho Bonito',
  'Rancho Rancho Verde',
  'Ranchería Sagrado Corazón',
  'Ranchería San Antonio',
  'Ranchería San Jorge',
  'Ranchería San José',
  'Ranchería Merfyl',
  'Ranchería San Ramón',
  'Ranchería Santa Rosa',
  'Ranchería 3 Hermanos',
  'Ranchería Altamira',
  'Ranchería Aníbal Moguel Farrera',
  'Ranchería Bellamira',
  'Equipamiento Antonio Narro (Universidad Autónoma Agraria)',
  'Ranchería Cielo Azul',
  'Ranchería Cuba',
  'Ranchería El Amate',
  'Ranchería El Caoba',
  'Ranchería El Chino',
  'Ranchería El Ciprés',
  'Ranchería El Dorado',
  'Ranchería El Duraznillo',
  'Ranchería El Higuito',
  'Rancho Los Cedros',
  'Ranchería El Manulltial',
  'Ranchería El Mirador',
  'Colonia El Muray',
  'Ranchería El Paso (Casa Hogar)',
  'Ranchería El Quijote',
  'Rancho Santa Rita la Paloma',
  'Ranchería El Saltillo',
  'Ranchería El Triunfo',
  'Ranchería Guillermo Ramos',
  'Ranchería Jorge Burguete',
  'Ranchería La Candelaria',
  'Ranchería La Ciénega',
  'Ranchería La Claudia (Los Cocodrilos)',
  'Ranchería La Enramada',
  'Rancho El Vergel',
  'Ranchería La Esperanza Fracción Dos',
  'Ranchería La Gloria',
  'Ranchería La Granada',
  'Ranchería La Habana',
  'Ranchería La Muralla',
  'Ranchería La Piedad',
  'Ranchería Las Delicias',
  'Ranchería Las Maravillas',
  'Ranchería Las Minas',
  'Ranchería Leopoldo Meza P.',
  'Ranchería Los Ángeles',
  'Rancho San Antonio',
  'Ranchería Los Toritos',
  'Ranchería Monte Cristo',
  'Rancho La Esperanza',
  'Ranchería Ocotlán',
  'Rancho Avimarca',
  'Ranchería Piedra Roja',
  'Ranchería Purísima Concepción (Loma Colorada)',
  'Ranchería Rancho Escondido',
  'Ranchería Rancho Francisca',
  'Ranchería Rancho Quemado',
  'Ranchería Rancho Verde',
  'Ranchería San Francisco',
  'Ranchería San Juan del Río',
  'Ranchería San Juditas',
  'Rancho Quinta Pedacito de Cielo',
  'Ranchería Santa Clara',
  'Ranchería Santa Isabel',
  'Rancho Santa Rita',
  'Ranchería Santa Patricia',
  'Ranchería Santa Rita Laguna Seca',
  'Ranchería Santa Rita Uno',
  'Ranchería Todos Santos',
  'Ranchería Tres Piedras',
  'Rancho La Escondida',
  'Ranchería Veracruz',
  'Colonia Vista Hermosa',
  'Equipamiento Émili',
  'Ranchería Alimentos Ejidal [Procesadora]',
  'Ranchería Casa Blanca',
  'Ranchería Dos Hermanos',
  'Ranchería Durango',
  'Rancho Emanuel',
  'Ranchería El Deseo (Mario Toledo C.)',
  'Ranchería El Hojamán',
  'Ranchería El Potrillo',
  'Ranchería El Tomatal',
  'Ranchería El Tronconal',
  'Rancho Rogelio Ríos',
  'Ranchería Jardines del Bosque',
  'Ranchería La Lomita',
  'Rancho Las Piñuelas',
  'Rancho San Francisco el Nopal',
  'Ejido Los Limones',
  'Ranchería Los Mangos',
  'Ranchería Los Pocitos',
  'Ranchería Monte Claro Santa Cruz',
  'Ranchería Romi',
  'Ranchería San Antonio',
  'Ranchería San Isidro las Piñuelas',
  'Ranchería Santa Rosa',
  'Ranchería Santa Teresita',
  'Ranchería Sin Pensar',
  'Ranchería Tacuazín',
  'Pueblo Lázaro Cárdenas',
  'Equipamiento CERESO 14 (El Amate)',
  'Ranchería Cinco Hermanos',
  'Ranchería Dos Hermanos',
  'Ranchería El Buen Pastor',
  'Ranchería El Milagro',
  'Ranchería El Novillero',
  'Ranchería La Escondida',
  'Ranchería La Mochita',
  'Ranchería La Odisea',
  'Ranchería La Sidra',
  'Ranchería Las Pitayas',
  'Ranchería Los Álamos',
  'Ranchería Los Tamarindos',
  'Ranchería Mesitalia',
  'Ranchería Peña de Horeb',
  'Ranchería Rusbel Cruz P.',
  'Ranchería San Antonio',
  'Ranchería San José',
  'Ranchería San Juan de Dios',
  'Ranchería San Ricardo',
  'Ranchería Santa Martha',
  'Ranchería Señor Rufino',
  'Ranchería Villa de los Álamos',
  'Ranchería Villahermosa',
  'Ranchería El Balsamar',
  'Ranchería El Brasil',
  'Ranchería La Gavia',
  'Ranchería La Isleta',
  'Rancho El Limoncito',
  'Ranchería Morelia',
  'Ranchería Ojo de Agua',
  'Ranchería San Ricardo',
  'Ranchería Xochimilco',
  'Ranchería Zapote Negro',
  'Colonia Mérida',
  'Colonia Integral Adolfo López Mateos',
  'Colonia La Asunción',
  'Ranchería 3 Diamantes',
  'Ranchería Brasilia',
  'Ranchería Buenavista',
  'Ranchería Cinco de mayo',
  'Colonia El Carmen',
  'Ranchería El Carrizal',
  'Ranchería El Lienzo',
  'Ranchería El Manguito',
  'Ranchería El Porvenir',
  'Ranchería El Recuerdo',
  'Ranchería El Siete (El Cero)',
  'Ranchería El Trece',
  'Ranchería El Triángulo',
  'Ranchería El Zakura',
  'Colonia Gracias a Dios',
  'Rancho Guadalupe',
  'Rancho La Gloria',
  'Finca La Razón',
  'Rancho La Valdivia',
  'Ranchería Las Flores',
  'Ranchería Las Margaritas',
  'Ranchería Las Vegas',
  'Ranchería Monarcas',
  'Ranchería Ocotlán',
  'Ranchería Piedra Pintada',
  'Ranchería Puerto Barrio',
  'Ranchería Rancho Escondido',
  'Ranchería San Diego',
  'Ranchería San Ignacio',
  'Ranchería San José',
  'Ranchería San José (El Cuajilote)',
  'Ranchería San Luis',
  'Ranchería San Martín',
  'Ranchería San Miguel',
  'Ranchería San Rafael',
  'Ranchería San Ramón',
  'Ranchería Santa Clara',
  'Ranchería Santa Lucía',
  'Ranchería Santa Martha',
  'Ranchería Santa Rosa',
  'Ranchería Santiago',
  'Ranchería Tierra Bendita',
  'Barrio San Francisco',
  'Colonia Emiliano Zapata',
  'Ranchería Alta Unión',
  'Ranchería Amando Borraz Ochoa',
  'Rancho Gracias a Dios',
  'Ranchería Bellavista',
  'Ranchería Buenavista',
  'Ranchería Buenos Aires',
  'Ranchería Casa Blanca',
  'Ranchería Chicozapote',
  'Ranchería Chicozapote las Casetas',
  'Colonia Gómez',
  'Ranchería Corral Falso',
  'Ranchería El Aguacate',
  'Ranchería El Caoba',
  'Ranchería El Caracol',
  'Rancho El Carmen',
  'Ranchería El Carrizalillo',
  'Ranchería El Huanacastle',
  'Ranchería El Jordán',
  'Ranchería El Majagual',
  'Ranchería El Patio',
  'Ranchería El Perú',
  'Ranchería El Porvenir',
  'Colonia El Progreso',
  'Ranchería El Saltillito',
  'Ranchería El Sauce',
  'Ranchería El Sauz',
  'Ranchería Eladio Trinidad Natarén',
  'Ranchería Guachipilín',
  'Ranchería Guadalupe',
  'Ranchería Horno Blanco',
  'Ranchería La Argentina',
  'Ranchería La Cabaña',
  'Rancho En el Nombre de Dios',
  'Ranchería La Cieneguilla',
  'Ranchería La Diana',
  'Ranchería La Gloria',
  'Ranchería La Herradura',
  'Ranchería La Historia',
  'Ranchería La Jabalina',
  'Ranchería 29 de Diciembre',
  'Ranchería La Mora',
  'Ranchería La Vueltona',
  'Ranchería Las Delicias',
  'Ranchería Las Margaritas',
  'Ranchería Las Pilas (Santa Úrsula)',
  'Ranchería Los Higos',
  'Colonia Las Anonas',
  'Ranchería Los Potrillos',
  'Colonia Mariano Pérez Díaz (La Joya)',
  'Colonia Nueva Esperanza 2da. Sección',
  'Ranchería Pénjamo',
  'Ranchería Plan de Guadalupe Dos',
  'Ranchería Rancho Chico',
  'Ranchería Sagrado Corazón de Jesús',
  'Ranchería San Antonio',
  'Ranchería San Antonio del Río',
  'Ranchería San Francisco Hojamán',
  'Ranchería San Antonio (Lindavista)',
  'Ranchería San José Betania',
  'Ranchería San Juan',
  'Ranchería San Judas (San Jacinto)',
  'Ranchería San Rafael',
  'Ranchería San Vicente',
  'Ranchería Santa Julia',
  'Ranchería Santa Martha',
  'Ranchería Tres Piedras',
  'Ranchería El Tuzal',
  'Colonia Villa del Río',
  'Colonia Abelardo L Rodriguez',
  'Ranchería David Nivón Escobar',
  'Ranchería El Capricho',
  'Ranchería El Caracol',
  'Ranchería El Manguito',
  'Ranchería El Milagro',
  'Ranchería El Pensamiento',
  'Ranchería El Recuerdo',
  'Colonia San Antonio del Valle',
  'Ranchería El Zapote de Abajo',
  'Ranchería El Zapote de Abajo (Desvio de Abelardo)',
  'Colonia El Zapote de Arriba',
  'Ranchería Humberto Mendoza',
  'Ranchería La Esperanza',
  'Ranchería La Victoria',
  'Ranchería Las Peñas',
  'Rancho Santa Rosa',
  'Ranchería Manuel Martínez',
  'Ranchería Productores de Sorgo',
  'Ranchería San Fernulldo',
  'Ranchería San José las Flores',
  'Rancho Santa Fe',
  'Ranchería Santa Ana',
  'Ranchería Santa Cruz',
  'Rancho Los Tres Juanes',
  'Ranchería Tres de Mayo',
  'Ranchería Vesubio',
  'Pueblo Pomposo Castellanos',
  'Colonia Esperanza de los Pobres',
  'Ranchería Ciénega de León',
  'Colonia 14 de Febrero',
  'Ranchería Buenos Aires',
  'Rancho San Juan',
  'Rancho Maranata',
  'Ranchería Córdova',
  'Barrio Crisálidas (Plan del Mango)',
  'Rancho San Antonio',
  'Ranchería El Egipto',
  'Ranchería El Nilo',
  'Ranchería El Norteño',
  'Rancho Mauira',
  'Ranchería El Palenque',
  'Barrio El Salvador',
  'Barrio El Tepeyac',
  'Ranchería El Triángulo',
  'Ranchería Fracción Nuevo Mundo',
  'Ranchería Francisco Villa',
  'Colonia Ingeniero Eloy Borras Aguilar',
  'Colonia Jorge de la Vega Domínguez (Las Pavas)',
  'Colonia Nuevo Amanecer Tenejapa',
  'Ranchería La Cabaña',
  'Ranchería La Calzada',
  'Ranchería La Divina Providencia',
  'Ranchería La Esperanza',
  'Ranchería La Orquídea',
  'Ranchería Las Dalias',
  'Ranchería Las Lajas',
  'Ranchería Las Murallas',
  'Colonia Las Palmas',
  'Ranchería Los Mangos',
  'Ranchería Los Olivos',
  'Rancho El Recuerdo',
  'Ranchería Monte Carlo',
  'Colonia Monte de los Olivos (La Mona)',
  'Colonia Monte Oreb',
  'Colonia Monte Sinaí Dos (El Fénix)',
  'Ranchería Nazareth',
  'Colonia Nueva Libertad',
  'Colonia Nueva Reforma (El Recreo)',
  'Ranchería Nueva Venecia',
  'Colonia Nuevas Maravillas',
  'Ranchería Nuevo Mundo',
  'Ranchería Paraje los Patos',
  'Ranchería San Ángel',
  'Ranchería San Joaquín',
  'Ranchería San José Puerto Rico',
  'Ranchería San Joseito',
  'Ranchería Santa Clara',
  'Ranchería Santa Lidia',
  'Ranchería Santa Rosa',
  'Ranchería Santo Domingo',
  'Colonia Villamorelos',
  'Colonia Vista Hermosa',
  'Ranchería Orizaba',
  'Ranchería Argentina',
  'Ranchería Bonullza',
  'Ranchería Buenavista',
  'Ranchería Centenario',
  'Ranchería Colima',
  'Ranchería Columpio',
  'Ranchería Concepción',
  'Ranchería Coronel Luis Espinosa',
  'Ranchería Cuatro Hermanos',
  'Ranchería El Bosque',
  'Ranchería El Calvario',
  'Ranchería El Cardel',
  'Ranchería El Chahuite',
  'Ranchería El Chiflido',
  'Ranchería El Cielito',
  'Ranchería El Desierto',
  'Ranchería El Dorado',
  'Ranchería El Ecuador',
  'Ranchería El Edén',
  'Ranchería El Gavilán',
  'Ranchería El Gran Chaparral',
  'Ranchería El Jardín',
  'Ejido El Milagro',
  'Colonia El Nuevo Edén',
  'Ranchería El Oasis',
  'Ranchería El Palomar',
  'Ranchería El Patio de Madera',
  'Ranchería El Pensamiento',
  'Ranchería El Pensamiento (El Arbolito)',
  'Ranchería El Porvenir',
  'Ranchería El Progreso',
  'Ranchería El Recreo',
  'Ranchería El Recuerdo',
  'Ranchería El Retiro',
  'Ranchería El Salvador',
  'Ranchería El Santuario',
  'Ranchería El Socorro',
  'Ranchería El Socorro Dos',
  'Ranchería El Triangulo',
  'Ranchería El Triángulo',
  'Rancho San José',
  'Ranchería El Triunfo',
  'Ranchería El Tule',
  'Ranchería La Esperanza',
  'Ranchería La Fortuna',
  'Ranchería La Gloria',
  'Ranchería La Granadita',
  'Ranchería La Higuera',
  'Ranchería La Ilusión',
  'Ranchería La Primavera',
  'Ranchería La Veleta',
  'Ranchería La Vuelta',
  'Ranchería Las Chinampinas',
  'Ranchería Las Crucecitas',
  'Ranchería Las Cruces',
  'Ranchería Las Flores',
  'Ranchería Las Jacarandas',
  'Ranchería Las Mercedes',
  'Ranchería Las Moradas',
  'Ranchería Las Reynas',
  'Ranchería Las Vegas',
  'Colonia Llano Grande',
  'Ranchería Los Cocos (Rancho Bonito)',
  'Ranchería Los Flamboyanes',
  'Ranchería Los Olachea (San Antonio Valdiviana)',
  'Ranchería Macuilapa',
  'Ranchería Miravalle',
  'Colonia Nueva Liberación',
  'Ranchería Paso Real',
  'Ranchería Patria Nueva',
  'Ranchería Poza Rica',
  'Ranchería Puerta Dorada',
  'Ranchería Rancho Alegre',
  'Ranchería Rancho Bonito',
  'Ranchería Rincón las Minas',
  'Ranchería Río Grande',
  'Ranchería San Agustín',
  'Ranchería San Andrés',
  'Ranchería San Antonio',
  'Ranchería San Carlos',
  'Ranchería San Damián',
  'Ranchería San Francisco',
  'Ranchería San Francisco (La Víbora)',
  'Ranchería San Jacinto',
  'Ranchería San José Montecristo',
  'Ranchería San Juanito',
  'Colonia San Marcos',
  'Ranchería San Rafael',
  'Ranchería San Ramón',
  'Ranchería San Roque',
  'Rancho Santa Ana',
  'Ranchería Santa Anita',
  'Ranchería Santa Cecilia',
  'Ranchería Santa Clara',
  'Ranchería Santa Elena',
  'Ranchería Santa Martha',
  'Ranchería Santa Rita',
  'Ranchería Santa Teresa',
  'Ranchería Santo Domingo',
  'Ranchería Solo Dios',
  'Ranchería Tierra Blanca',
  'Ranchería Tres Hermanos',
  'Ranchería Último de Mayo',
  'Ranchería Unión Pastrana',
  'Ranchería Villa Corona',
  'Ranchería Zacualpa',
  'Ranchería Amatán (Cerro Brujo)',
  'Ranchería El Paraiso',
  'Colonia Ignacio Zaragoza',
  'Ranchería San Pedro',
  'Colonia San Sebastián',
  'Colonia Constitución (El Chayotal)',
  'Colonia Las Merceditas',
  'Ranchería Adolfo López Ruiz',
  'Ranchería Alberto Valencia',
  'Ranchería Agua Dulce',
  'Ranchería Amado González Muñoz',
  'Ranchería Cuatro de Agosto',
  'Ranchería El Aguaje',
  'Ranchería El Ahogadero',
  'Ranchería El Chichonal',
  'Ranchería El Chintule',
  'Ranchería El Chintulito',
  'Ranchería El Coyolar',
  'Ranchería El Hular',
  'Ranchería El Ingenio',
  'Ranchería El Jobal',
  'Ranchería El Manguito',
  'Ranchería El Milagro',
  'Ranchería El Mirador',
  'Ranchería El Naranjal',
  'Ranchería El Palmar',
  'Ranchería El Paso la Costosa',
  'Ranchería El Recuerdo',
  'Ranchería El Riego',
  'Colonia Felipe Ángeles',
  'Ranchería Gilberto Morales',
  'Ranchería Guadalupe',
  'Colonia Guadalupe Victoria Uno (La Herradura)',
  'Ranchería Guillermo Velázquez',
  'Ranchería La Bugambilia',
  'Ranchería La Ceiba',
  'Ranchería La Ñagara',
  'Ranchería La Noria',
  'Ranchería La Peña',
  'Ranchería La Peñita',
  'Ranchería La Selva',
  'Ranchería La Sombra',
  'Ranchería La Victoria',
  'Ranchería Las Ánimas',
  'Ranchería Las Palmas',
  'Ranchería Los Aguacates',
  'Ranchería Los Cocos',
  'Ranchería Los Corazones',
  'Ranchería Los Limones',
  'Ranchería Los Limones (Tetesquite)',
  'Ranchería Los Pinos',
  'Ranchería Los Potrillos',
  'Ranchería Miguel Chacón',
  'Ranchería Monarca',
  'Colonia Monte Sinaí Dos (Los Horcones)',
  'Ranchería Piedra Azul',
  'Ranchería Río Negro (Pueblo Viejo)',
  'Ranchería Rosember López Escobar',
  'Ranchería Salto de Agua',
  'Ranchería San Antonio',
  'Ranchería San Antonio del Carmen',
  'Ranchería San Carlos',
  'Ranchería San Jesús',
  'Ranchería San José Montenegro',
  'Ranchería San José Naranjal',
  'Ranchería San Luis',
  'Ranchería Santa María',
  'Ranchería Santa Rosa',
  'Colonia Simón Bolívar (El Transval)',
  'Ranchería Soledad del Bosque',
  'Ranchería Agua Fría',
  'Colonia Adolfo López Mateos',
  'Ranchería Andrés Gómez',
  'Ranchería Antonio Díaz Ruiz',
  'Ranchería Antonio Gómez',
  'Rancho San Pedro',
  'Ranchería El Aguajón',
  'Ranchería El Arco',
  'Ranchería El Cucurucho',
  'Ranchería El Dorado',
  'Ranchería El Edén',
  'Ranchería El Ensueño',
  'Colonia El Medallin (Unesco)',
  'Ranchería El Otro Mundo',
  'Ranchería El Paraíso',
  'Ranchería El Platanillo',
  'Rancho El Porvenir',
  'Ranchería El Potrero',
  'Ranchería El Progreso',
  'Colonia El Rosario',
  'Ranchería El Zapote',
  'Ejido Emiliano Zapata',
  'Ranchería Encarnación Hernández L.',
  'Ranchería El Zapote 2',
  'Ranchería Framboyán',
  'Colonia General Cárdenas',
  'Ranchería Guadalupe',
  'Ranchería Juan Gómez Sánchez',
  'Ranchería La Bandera',
  'Ranchería La Cabaña',
  'Colonia La Herendira',
  'Ranchería La Panelita',
  'Ranchería La Sima',
  'Ranchería La Virginia',
  'Colonia Las Carmelitas',
  'Ranchería Las Gardenias',
  'Ranchería Las Láminas',
  'Ranchería Las Naranjas',
  'Ranchería Las Palmas',
  'Ranchería Las Perlas',
  'Ranchería Las Tres Marías',
  'Ranchería Lindavista',
  'Ranchería Los Alpes',
  'Colonia Los Horcones',
  'Colonia Los Joaquines',
  'Ranchería Los Limones',
  'Ranchería Los Tulipanes',
  'Ranchería Luis Díaz Aguilar',
  'Ranchería Luis O. Moreno H.',
  'Ranchería Marcos Gómez',
  'Rancho Los Mangos',
  'Ranchería Montecristo',
  'Colonia Monterrey',
  'Ranchería Nazareth',
  'Ranchería Ojo de Agua (Unesco)',
  'Ranchería San Antonio',
  'Ranchería San Cayetano',
  'Colonia Unidad Modelo',
  'Rancho San Juan de Dios',
  'Colonia Venustiano Carranza',
  'Ranchería Veracruz',
  'Ranchería Vista Alegre (El Mercadito)',
  'Barrio Santo Domingo',
  'Colonia Rosendo Salazar',
  'Ejido Nueva Tenochtitlán (Rizo de Oro)',
  'Ranchería Altamira',
  'Ranchería Bellalinda',
  'Ranchería La Verbena',
  'Ranchería Chapultepec',
  'Ranchería Cinco Cerros',
  'Colonia Corazón del Valle',
  'Ranchería El Amatillo',
  'Ranchería El Bernal',
  'Ranchería El Brillante',
  'Ranchería El Cafetal (Rancho Nuevo)',
  'Ranchería El Chahuitillo',
  'Ranchería El Consuelo',
  'Ranchería El Corazoncito',
  'Colonia El Danubio',
  'Ranchería El Edén',
  'Ranchería El Horizonte',
  'Ranchería El Ocote',
  'Ranchería El Oriente',
  'Ranchería El Platanillo',
  'Ranchería El Recuerdo',
  'Ranchería El Renegado (La Cabaña)',
  'Ranchería El Saltillo',
  'Ranchería El Sauz',
  'Ranchería El Sinaí',
  'Ranchería El Sueño',
  'Ranchería El Tesoro',
  'Ranchería El Zapotillo',
  'Rancho Guadalupe',
  'Ranchería Humoa',
  'Ranchería Jilotepec',
  'Ranchería La Cima',
  'Colonia La Libertad',
  'Colonia La Nueva España',
  'Ranchería La Vainilla',
  'Ranchería La Vibora',
  'Ranchería Las Brisas',
  'Ranchería Las Bugambilias',
  'Ranchería Las Canoitas Primera',
  'Ranchería Las Canoitas Segunda',
  'Ranchería Las Dos Gardenias',
  'Ranchería Las Jaquimas',
  'Ranchería Las Lluvias',
  'Ranchería Las Maravillas',
  'Ranchería Las Murallas',
  'Ranchería Las Palmas',
  'Ranchería Las Perlas',
  'Ranchería Las Pilas',
  'Ranchería Las Tasajeras',
  'Ranchería Lindavista',
  'Ranchería Los Andes',
  'Ranchería Los Clavelitos (Pilón de Azúcar)',
  'Ranchería Los Laureles',
  'Ranchería Los Miradores',
  'Ranchería Los Pinos',
  'Ranchería Nazareth',
  'Colonia Niños Héroes',
  'Ranchería Nueva Puebla',
  'Ranchería Nueva Vida',
  'Ranchería Pablo Salazar',
  'Ranchería Palo Blanco',
  'Ranchería Pénjamo',
  'Ranchería Rancho Alegre',
  'Ranchería Rancho Cupido',
  'Ranchería Rincón Sandía',
  'Ranchería Río Limón (Los Mangos)',
  'Ranchería Sagrado Corazón de Jesús',
  'Ranchería San Antonio',
  'Ranchería San Fernulldo',
  'Ranchería San Isidro',
  'Ranchería San Joaquín',
  'Ranchería San José la Verdad',
  'Ranchería San Juan',
  'Ranchería San Luis',
  'Ranchería San Mateo',
  'Ranchería San Miguel',
  'Ranchería San Pedro de las Palmas',
  'Colonia San Pedro de las Palmas Dos',
  'Ranchería San Vicente',
  'Ranchería Santa Cruz',
  'Ranchería Santa Fe',
  'Ranchería Siete Hermanos',
  'Ranchería Tatachepe',
  'Colonia Valle de Corzo (San Fernulldo)',
  'Ranchería Veinte de Noviembre',
  'Colonia Yerbasanta',
  'Colonia La Florida',
  'Colonia El Mirador',
  'Colonia José Castillo Tielmans',
  'Colonia Nuevo Jerusalén',
  'Colonia Roberto Barrios',
  'Colonia Tehuacan',
  'Ranchería Agua Escondida',
  'Ranchería Alaska',
  'Ranchería Alta Vista',
  'Ranchería Alto la Alvarda',
  'Ranchería Betania',
  'Colonia Bethel',
  'Ranchería El Aguajón',
  'Ranchería El Calvario',
  'Ranchería El Capulín',
  'Ranchería El Estoraque (El Organal)',
  'Ranchería El Faro',
  'Ranchería El Guamúchil',
  'Ranchería El Jobito',
  'Ranchería El Pensamiento',
  'Ranchería El Pencil',
  'Ranchería El Porvenir',
  'Ranchería El Rubí',
  'Ranchería El Suspiro',
  'Ranchería Juan Carral',
  'Ranchería La Esmeralda',
  'Ranchería La Guacamaya',
  'Ranchería La Herradura',
  'Ranchería La Lagunita',
  'Ranchería La Naranja',
  'Ranchería La Selva',
  'Ranchería Las Casitas',
  'Ranchería Las Limas',
  'Ranchería Las Margaritas',
  'Ranchería Los Ángeles',
  'Ranchería Miramar (El Tempisque)',
  'Ranchería Monserrat',
  'Ranchería Monterrey',
  'Ranchería nullcital',
  'Colonia Nuevo Coyoacán',
  'Ranchería Rancho Nuevo',
  'Ranchería Rincón Antonio',
  'Ranchería San Bartolo',
  'Ranchería San Lucas',
  'Colonia Santiago',
  'Rancho San Pablo Chamiapa',
  'Ranchería El Aguacate',
  'Ranchería El Paraíso',
  'Ranchería El Porvenir (El Rosario)',
  'Ranchería El Retiro',
  'Ranchería El Zapotal (Santa Rosa)',
  'Ranchería La Esperanza',
  'Colonia La Marqueza',
  'Ranchería La Selva',
  'Ranchería Las Cuevas',
  'Ranchería Nueva Pimienta',
  'Colonia Palomares',
  'Colonia Pimienta Berlín',
  'Ranchería San Fernulldo',
  'Ranchería Venecia',
  'Colonia Francisco I Madero',
  'Colonia Triunfo de Madero',
  'Colonia Estoracón',
  'Colonia Guadalupe Victoria',
  'Ranchería La Candelaria',
  'Ranchería Adrián Pérez',
  'Ranchería Altamira',
  'Ranchería Belén (La Peñita)',
  'Ranchería Buenavista',
  'Ranchería El Bosque',
  'Ranchería El Cuajilote',
  'Ranchería El Magueyal',
  'Ranchería El Mirador',
  'Ranchería El Naranjo',
  'Ranchería El Oasis',
  'Ranchería El Ocote',
  'Ranchería El Perú',
  'Ranchería Francisco Arellano',
  'Ranchería Guerrero (Ocho de Marzo)',
  'Colonia Jacinto Tirado',
  'Ranchería Javier López Moreno',
  'Ranchería La Aceitera',
  'Ranchería La Argentina',
  'Ranchería La Bizca',
  'Ranchería La Esperanza',
  'Ranchería La Mora',
  'Ranchería La Posta',
  'Ranchería La Ribera',
  'Ranchería Las Brisas',
  'Ranchería Las Margaritas',
  'Ranchería Las Nubes',
  'Ranchería Los Amates',
  'Ranchería Los Hermanos',
  'Ranchería Los Mangos',
  'Ranchería Los Ocotones [Aserradero]',
  'Ranchería Los Tulipanes',
  'Ranchería Martín Ríos',
  'Ranchería Pascual López',
  'Ranchería Quintilo Velázquez L',
  'Ranchería Rancho Alegre',
  'Ranchería Rancho Escondido',
  'Ranchería San Andrés',
  'Ranchería San Antonio',
  'Ranchería San Jacinto',
  'Ranchería San Mateo',
  'Ranchería Santa Inés',
  'Ranchería Santa Lucia',
  'Ranchería Santa Martha',
  'Ranchería Sonora',
  'Colonia Uña de Gato',
];

// ── Roles del panel administrativo ───────────────────────────────────────────

const PANEL_ROLES = [
  {
    name: 'SUPERADMIN',
    description: 'Acceso total al sistema. Gestión de usuarios y configuración.',
  },
  { name: 'COORDINADOR', description: 'Coordina operadores y puede ver reportes avanzados.' },
  { name: 'OPERADOR_CHAT', description: 'Atiende conversaciones de ciudadanos en el chat.' },
  { name: 'ANALISTA', description: 'Acceso de solo lectura a datos y reportes.' },
] as const;

async function seedNeighborhoods(): Promise<void> {
  for (const name of neighborhoodNames) {
    await prisma.neighborhood.upsert({
      where: { name },
      update: { nameLower: toNameLower(name) },
      create: { name, nameLower: toNameLower(name) },
    });
  }
  console.log(`✅ ${neighborhoodNames.length} neighborhoods seeded`);
}

async function seedRoles(): Promise<void> {
  for (const role of PANEL_ROLES) {
    await prisma.role.upsert({
      where: { name: role.name },
      update: { description: role.description },
      create: { name: role.name, description: role.description },
    });
  }
  console.log(
    `✅ ${PANEL_ROLES.length} roles seeded: ${PANEL_ROLES.map((r) => r.name).join(', ')}`,
  );
}

async function seedSuperadmin(): Promise<void> {
  const email = process.env.SUPERADMIN_EMAIL ?? 'admin@vozcuidadana.mx';
  const password = process.env.SUPERADMIN_PASSWORD ?? 'changeme_in_production_123!';
  const fullName = process.env.SUPERADMIN_FULL_NAME ?? 'Super Administrador';

  const superadminRole = await prisma.role.findUnique({ where: { name: 'SUPERADMIN' } });
  if (!superadminRole) {
    throw new Error('Rol SUPERADMIN no encontrado — corré seedRoles primero');
  }

  const existing = await prisma.user.findUnique({ where: { email } });

  if (existing) {
    console.log(`ℹ️  Superadmin ya existe: ${email}`);
    return;
  }

  const hashedPassword = await bcrypt.hash(password, 12);

  await prisma.user.create({
    data: {
      email,
      hashedPassword,
      fullName,
      isActive: true,
      userRoles: {
        create: [{ roleId: superadminRole.id }],
      },
    },
  });

  console.log(`✅ Superadmin creado: ${email}`);
  console.log(`   ⚠️  Cambiá la contraseña en producción via SUPERADMIN_PASSWORD env var`);
}

async function main(): Promise<void> {
  console.log('🌱 Seeding database...');

  await seedNeighborhoods();
  await seedRoles();
  await seedSuperadmin();

  console.log('🎉 Seed complete');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
